StarterProjectV2/ViewModels/SlotManagementView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using StarterProjectV2.Models;

namespace StarterProjectV2.ViewModels
{
    public class SlotManagementView
    {
        public List<SlotInfo> SlotList { get; set; }
        public string TaskRoles { get; set; }
    }
}

StarterProjectV2/Controllers/SlotController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using StarterProjectV2.Models;
using StarterProjectV2.ViewModels;

namespace StarterProjectV2.Controllers
{
    public class SlotController : Controller
    {
        public bool IsUserLoggedIn()
        {
            //return true;
            return !string.IsNullOrEmpty(Session[SessionKeys.USERNAME] as string);
        }

        [HttpGet]
        public ActionResult SlotManagement()
        {
            if (!IsUserLoggedIn())
                return RedirectToAction("Login", "Accounts");
            Common.EmailSending("omeca13@gmail.com", "Hello test", "Testing Webmail");
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                //string taskId = db.Tasks.Where(u => u.TaskPath == "Ownersinfo\\ownermanagement").Select(u => u.TaskId).FirstOrDefault();
                string taskId = db.Tasks.Where(u => u.TaskPath == "Slot\\SlotManagement").Select(u => u.TaskId).FirstOrDefault();
                var myRoleList = (List<UserRole>)Session[SessionKeys.ROLE_LIST];

                string taskRoles = "";
                foreach (var tasks in myRoleList)
                {
                    if (tasks.TaskId == taskId)
                    {
                        taskRoles = tasks.Details;
                    }
                }


                if (taskRoles == "")
                {
                    return View("Error");
                }

                var model = new SlotManagementView
                {
                    SlotList = db.SlotInfos.ToList(),
                    TaskRoles = taskRoles
                };
                return View(model);
            }
        }
        public PartialViewResult SearchUsers(string searchText)
        {
            

            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                //List<SlotInfo> users = GetUsers();
               
                var users = db.SlotInfos.ToList();
                List<SlotInfo> searchedOwner = new List<SlotInfo>();
                var result = users;
            if (!string.IsNullOrEmpty(searchText))
            {
                result = users.Where(a => a.SlotName.ToLower().Contains(searchText.ToLower())).ToList();
                }
                return PartialView("_GridView", result);
            }
           
        }
        
        [HttpGet]
        public ActionResult SlotCreate()
        {
            if (!IsUserLoggedIn())
                return RedirectToAction("Login", "Accounts");
            return View();
        }

        [HttpGet]
        public ActionResult SlotEdit(string slotId)
        {
            if (!IsUserLoggedIn())
                return RedirectToAction("Login", "Accounts");
            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {
                var slotInDb = adbc.SlotInfos.Where(r => r.SlotId == slotId).FirstOrDefault();


                //Modifying the from dates and todates before sending to the View
                var year = (int.Parse(slotInDb.FromDate.ToString().Split('-')[0]));
                var month = (int.Parse(slotInDb.FromDate.ToString().Split('-')[1]));
                var updated_month = month.ToString();
                if (month.ToString().Length == 1) updated_month = "0" + month.ToString();
                var newFromDate = year.ToString() + "-" + updated_month;

                var year2 = (int.Parse(slotInDb.ToDate.ToString().Split('-')[0]));
                var month2 = (int.Parse(slotInDb.ToDate.ToString().Split('-')[1]));
                var updated_month2 = month2.ToString();
                if (month2.ToString().Length == 1) updated_month2 = "0" + month2.ToString();
                var newToDate = year2.ToString() + "-" + updated_month2;

               
                SlotInfo mdl = new SlotInfo()
                {
                    SlotId = slotInDb.SlotId,
                    SlotName = slotInDb.SlotName,
                    SlotOtherDefinitions = slotInDb.SlotOtherDefinitions,
                    FromDate = newFromDate,
                    ToDate = newToDate
                    //(int.Parse(slotInDb.ToDate.ToString().Split('-')[0]) + int.Parse(slotInDb.ToDate.ToString().Split('-')[1])).ToString()
                };
                return View("SlotCreate", mdl);
            }
        }

        [HttpPost]
        public ActionResult SlotAddorEdit(SlotInfo info)
        {
            if (!IsUserLoggedIn())
                return RedirectToAction("Login", "Accounts");
            

            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {
                var slotId = "";
                //OwnersInfo info = model.Owners;
                //new Owner : Add Mode 
                if (string.IsNullOrEmpty(info.SlotId))
                {
                    var slotList = adbc.SlotInfos.ToList();
                    var slotIdList = new List<int>();
                    foreach (var slots in slotList)
                    {
                        slotIdList.Add(int.Parse(slots.SlotId.ToString().Split('-')[1]));
                    }

                    var slotToken = slotList.Count();
                    if (slotToken > 0)
                    {
                        slotIdList.Sort();
                        slotToken = slotIdList[slotIdList.Count - 1];
                    }

                    slotToken++;
                    slotId = "SLOT-" + slotToken;


                    //Formatting the fromdate and todates
                    info.FromDate = info.FromDate + "-01";
                    var year = int.Parse(info.ToDate.ToString().Split('-')[0]);
                    var month = int.Parse(info.ToDate.ToString().Split('-')[1]);
                    var day = 0;
                    if (month == 2) day = 28;
                    else if (month % 2 == 1) day = 31;
                    else if (month % 2 == 0) day = 30;

                    if ((year % 4 == 0 && year % 100 != 0)||(year % 400 == 0))
                        day = day + 1;  //leap year
                    
                    info.ToDate = info.ToDate + "-" + day.ToString();





                    SlotInfo model = new SlotInfo()
                    {
                        SlotId = slotId,
                        SlotName = info.SlotName,
                        SlotOtherDefinitions = info.SlotOtherDefinitions,
                        ToDate = info.ToDate,
                        FromDate = info.FromDate
                    };
                    adbc.SlotInfos.Add(model);
                    adbc.SaveChanges();
                } //existing Owner: Edit Mode
                else
                {
                    var slotInDb = adbc.SlotInfos.SingleOrDefault(r => r.SlotId == info.SlotId);

                    slotId = slotInDb.ToString();



                    //Formatting the fromdate and todates
                    info.FromDate = info.FromDate + "-01";
                    var year = int.Parse(info.ToDate.ToString().Split('-')[0]);
                    var month = int.Parse(info.ToDate.ToString().Split('-')[1]);
                    var day = 0;
                    if (month == 2) day = 28;
                    else if (month % 2 == 1) day = 31;
                    else if (month % 2 == 0) day = 30;

                    if ((year % 4 == 0 && year % 100 != 0) ||(year % 400 == 0))
                        day = day + 1;  //leap year
                    
                    info.ToDate = info.ToDate + "-" + day.ToString();

                    


                    slotInDb.SlotName = info.SlotName;
                    slotInDb.FromDate = info.FromDate;
                    slotInDb.ToDate = info.ToDate;
                    slotInDb.SlotOtherDefinitions = info.SlotOtherDefinitions;
                }
                adbc.SaveChanges();
                return RedirectToAction("SlotManagement");
            }
        }



        [HttpGet]
        public ActionResult SlotView(string slotId)
        {
            if (!IsUserLoggedIn())
                return RedirectToAction("Login", "Accounts");


            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {

                var model = adbc.SlotInfos.Where(p => p.SlotId == slotId).SingleOrDefault();
                SlotInfo slotModel = new SlotInfo()
                {
                    FromDate = model.FromDate,
                    ToDate = model.ToDate,
                    SlotOtherDefinitions = model.SlotOtherDefinitions,
                    SlotId = model.SlotId,
                    SlotName = model.SlotName
                };

                return View("SlotView", slotModel);
            }
        }


        [HttpPost]
        public ActionResult SlotDelete(string slotId)
        {
            if (!IsUserLoggedIn())
                return RedirectToAction("Login", "Accounts");
            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {
                var SlotInDb = adbc.SlotInfos.Where(r => r.SlotId == slotId).FirstOrDefault();
                adbc.SlotInfos.Remove(SlotInDb);
                adbc.SaveChanges();
                return RedirectToAction("SlotManagement");
            }
        }
    }
}

StarterProjectV2/Views/Slot/SlotCreate.cshtml
@model StarterProjectV2.Models.SlotInfo
@{
    ViewBag.Title = "Slot Create";
}
@section HEADERJS{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        
}
@section FOOTERJS{
    <script src="~/Content/vendors/js/toastr.min.js"></script>
    <script src="~/Content/vendors/js/coreui.min.js"></script>

}

<div class="row justify-content-center ">
    <div class="card col-12">
        <div class="card-body">
            <h1 class="text-center mb-5" style="color:indianred">Slot Create Form</h1>
            <p class="text-muted"></p>

            @using (Html.BeginForm("SlotAddorEdit", "Slot", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @*@Model.FromDate
                @Model.ToDate*@
                <div class="form-group row mb-3">
                    @*@Html.LabelFor(m => m.SlotName, new { @class = "col-sm-3 col-lg-2 col-md-3  col-form-label" })*@
                    <label class="col-sm-3 col-lg-2 col-md-3  col-form-label">Slot Name</label>
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        @Html.TextBoxFor(m => m.SlotName, new { @class = "form-control", placeholder = "Slot Name", type = "text" })
                    </div>
                </div>


                <div class="form-group row mb-3">

                    @*@Html.LabelFor(m => m.FromDate, new { @class = "col-sm-3 col-lg-2 col-md-3 col-form-label" })*@
                    <label class="col-sm-3 col-lg-2 col-md-3  col-form-label">From Date</label>
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        @Html.TextBoxFor(m => m.FromDate,
                            new { @class = "form-control input-group date", placeholder = "From Date", type = "month" })
                    </div>
                </div>
                <div class="form-group row mb-3">

                    @*@Html.LabelFor(m => m.ToDate, new { @class = "col-sm-3 col-lg-2 col-md-3 col-form-label" })*@
                    <label class="col-sm-3 col-lg-2 col-md-3  col-form-label">To Date</label>
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        @Html.TextBoxFor(m => m.ToDate,
                            new { @class = "form-control", placeholder = "To Date", type = "month" })
                    </div>
                </div>

                <div class="form-group row mb-3">
                    @*@Html.LabelFor(m => m.SlotOtherDefinitions, new { @class = "col-sm-3 col-lg-2 col-md-3 col-form-label" })*@
                    <label class="col-sm-3 col-lg-2 col-md-3  col-form-label">Slot Other Definitions</label>
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        @Html.TextBoxFor(m => m.SlotOtherDefinitions, new { @class = "form-control", placeholder = "Slot Other Definitions", type = "text" })
                    </div>
                </div>

                @Html.HiddenFor(m => m.SlotId, new { @id = "SlotId" })

                <div class="row">
                    <div>
                        <button type="submit" class="btn btn-primary m-1">Submit</button>
                    </div>
                    <div>
                        <button type="button" class="btn btn-danger m-1">Reset</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>


@*<div class="input-append date" id="datepicker" data-date="01-2019"
     data-date-format="dd-mm-yyyy">

    <input type="text" name="date">
    <span class="add-on"><i class="icon-th"></i></span>
</div>
<script type="text/javascript">
    $("#datepicker").datepicker({
        viewMode: 'years',
        format: "mm-yyyy",
        startView: "months",
        minViewMode: "months"
    });
</script>*@

<script>
    $(document).ready(function () {
        $("#newItem").remove();

        $("#editItem").remove();
        $("#saveItem").remove();
        $("#deleteItem").remove();
        $('#printItem').click(function () {
            window.print();
        });

        $('#reloadItem').click(function () {
            location.reload();
        });
        $("#reportItem").remove();
        $("#dashboardItem").click(function () {
            //document.location = 'Url.Action("ExportExcel", "OwnersInfo")';
        });
    });

</script>

StarterProjectV2/Views/Slot/SlotManagement.cshtml
@model StarterProjectV2.ViewModels.SlotManagementView
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
@section HEADERJS{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
}

@section FOOTERJS{
    <script src="~/Content/vendors/js/toastr.min.js"></script>
    <script src="~/Content/vendors/js/coreui.min.js"></script>
}
<!DOCTYPE html>

@*<h2 class="text-center" style="color:indianred">@ViewData["Title"]</h2>*@



    <div class="row">
        <div class="col-sm-12">
            <div class="form-inline pull-left">

                @*<label>Search</label>*@
                <input type="text" name="txtSearch" value="" class="form-control" id="txtSearch" />
                <button type="button" id="txtSearchBtn">Search</button>
            </div>
        </div>
        <div id="gridUsers"></div>
    </div>
    <script ssrc="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        getUsers();
        $('#txtSearch').keypress(function (e) {
            var key = e.which;
            if (key == 13)  // the enter key code
            {
                getUsers();
            }
        });   

        $('#txtSearchBtn').click(function () {
            getUsers();
        });

    @*$(() => {
        getUsers();
        $('#txtSearch').on('keyup', () => {
            getUsers();
        });
    });*@
    function getUsers() {
        $.ajax({
            url: '@Url.Action("SearchUsers", "Slot")',
            datatype: 'html',
            method: 'GET',
            data: { searchText: $('#txtSearch').val() },
            success: function (res) {
                $('#gridUsers').html('').html(res);
            },
            error: function (err) {
                console.log(err);
            }
        })
    }
    </script>

 



<script>
    $(document).ready(function() {
        var taskRoles = "@Model.TaskRoles";
        if (taskRoles[0] == '0') {
            $('table tr').find('td:eq(0),th:eq(0)').remove();
            if (taskRoles[3] == '0') {
                $('table tr').find('td:eq(0),th:eq(0)').remove();
                if (taskRoles[4] == '0') {
                    $('table tr').find('td:eq(0),th:eq(0)').remove();
                }
            } else {
                if (taskRoles[4] == '0') {
                    $('table tr').find('td:eq(1),th:eq(1)').remove();
                }
            }
        } else {
            if (taskRoles[3] == '0') {
                $('table tr').find('td:eq(1),th:eq(1)').remove();
                if (taskRoles[4] == '0') {
                    $('table tr').find('td:eq(1),th:eq(1)').remove();
                }
            } else {
                if (taskRoles[4] == '0') {
                    $('table tr').find('td:eq(2),th:eq(2)').remove();
                }
            }
        }
        if (taskRoles[1] == '0') {
            $("#newItem").remove();
        }
    });
</script>

<script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
</script>



<script>
    var clicked = false;
    $("#Select").on("click", function () {
        $(".form-check-input").prop("checked", !clicked);
        clicked = !clicked;
    });



    $(document).ready(function() {
        $("#newItem").click(function() {
            document.location = '@Url.Action("SlotCreate", "Slot")';
        });

        $("#editItem").remove();
        $("#saveItem").remove();
        $("#deleteItem").remove();
        $('#printItem').click(function(){
            window.print();
        });

        $('#reloadItem').click(function() {
            location.reload();
        });

        @*$("#dashboardItem").click(function() {
            document.location = '@Url.Action("ExportExcel", "OwnersInfo")';
        });*@
        $("#reportItem").remove();

    });


</script>



<script src="~/Content/vendors/js/jquery.min.js"></script>
<script src="~/Content/vendors/js/popper.min.js"></script>
<script src="~/Content/vendors/js/bootstrap.min.js"></script>
<script src="~/Content/vendors/js/pace.min.js"></script>
<script src="~/Content/vendors/js/toastr.min.js"></script>
<script src="~/Content/vendors/js/perfect-scrollbar.min.js"></script>
<script src="~/Content/vendors/js/coreui.min.js"></script>

StarterProjectV2/Views/Slot/SlotView.cshtml
@model StarterProjectV2.Models.SlotInfo
@{
    ViewBag.Title = "Slot Create";
}
@section HEADERJS{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
}
@section FOOTERJS{
    <script src="~/Content/vendors/js/toastr.min.js"></script>
    <script src="~/Content/vendors/js/coreui.min.js"></script>

}

<div class="row justify-content-center ">
    <div class="card col-12">
        <div class="card-body">
            <h1 class="text-center mb-5" style="color:indianred">Slot Create Form</h1>
            <p class="text-muted"></p>

            @using (Html.BeginForm("SlotAddorEdit", "Slot", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="form-group row mb-3">
                    @Html.LabelFor(m => m.SlotName, new { @class = "col-sm-3 col-lg-2 col-md-3  col-form-label" })
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        @Html.TextBoxFor(m => m.SlotName, new { @class = "form-control", placeholder = "Slot Name", type = "text", @readonly = "readonly" })
                    </div>
                    @*@Html.LabelFor(m => m.DateOfBirth, new { @class = "col-sm-3 col-lg-2 col-md-3 col-form-label" })
                        <div class="col-sm-3 col-lg-3 col-md-3">
                            @Html.TextBoxFor(m => m.DateOfBirth,
                                new { @class = "form-control", placeholder = "Date Of Birth", type = "date" })
                        </div>*@
                </div>


                <div class="form-group row mb-3">

                    @Html.LabelFor(m => m.FromDate, new { @class = "col-sm-3 col-lg-2 col-md-3 col-form-label" })
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        @Html.TextBoxFor(m => m.FromDate,
                            new { @class = "form-control", placeholder = "From Date", type = "date", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group row mb-3">

                    @Html.LabelFor(m => m.ToDate, new { @class = "col-sm-3 col-lg-2 col-md-3 col-form-label" })
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        @Html.TextBoxFor(m => m.ToDate,
                            new { @class = "form-control", placeholder = "To Date", type = "date", @readonly = "readonly" })
                    </div>
                </div>

                <div class="form-group row mb-3">
                    @Html.LabelFor(m => m.SlotOtherDefinitions, new { @class = "col-sm-3 col-lg-2 col-md-3 col-form-label" })
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        @Html.TextBoxFor(m => m.SlotOtherDefinitions, new { @class = "form-control", placeholder = "Slot Other Definitions", type = "text", @readonly = "readonly" })
                    </div>
                </div>

                @Html.HiddenFor(m => m.SlotId, new { @id = "SlotId" })

            }
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
    $("#newItem").remove();

    $("#editItem").remove();
    $("#saveItem").remove();
    $("#deleteItem").remove();
    $('#printItem').click(function () {
        window.print();
    });

    $('#reloadItem').click(function () {
        location.reload();
    });
    $("#reportItem").remove();
    $("#dashboardItem").click(function () {
    //document.location = 'Url.Action("ExportExcel", "OwnersInfo")';
    });
    });

</script>

StarterProjectV2/Views/Slot/_GridView.cshtml
@model List<StarterProjectV2.Models.SlotInfo>
<div class="container-fluid" style="margin-bottom: 0">
    <h2 class="text-center" style="color:indianred">@ViewData["Title"]</h2>
    <div class="table-responsive-lg ">
        <table id="mainTable" data-pagination="true" class="table table-hover table-dark" style="margin-bottom: 0">
            <thead class="bg-blue" style="color:white">
                <tr>
                    <th scope="col">View</th>
                    <th scope="col">Edit</th>
                    <th scope="col">
                        Delete
                    </th>
                    <th scope="col">Slot Id</th>
                    <th scope="col">Slot Name</th>
                    <th scope="col">From Date</th>
                    <th scope="col">To Date</th>
                    <th scope="col">Slot Other Definitions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var slot in Model)
                {
                    <tr>
                        <td>
                            <button type="button"
                                    class="btn btn-light"
                                    data-toggle="tooltip"
                                    data-placement="bottom"
                                    title="View"
                                    onclick="location.href = '@Url.Action("SlotView", "Slot", new { slotId=slot.SlotId})'">
                                <i class="icon-eye">
                                </i>
                            </button>
                        </td>
                        <td>
                            <button type="button"
                                    class="btn btn-light"
                                    data-toggle="tooltip"
                                    data-placement="bottom"
                                    title="Edit"
                                    onclick="location.href='@Url.Action("SlotEdit", "Slot", new { slotId=slot.SlotId})'">
                                <i class="icon-notebook">
                                </i>
                            </button>
                        </td>
                        <td>
                            @using (Html.BeginForm("SlotDelete", "Slot", new { slotId = slot.SlotId }, FormMethod.Post))
                            {
                                <button type="submit"
                                        class="btn btn-light"
                                        data-toggle="tooltip"
                                        data-placement="bottom"
                                        onclick="ConfirmDelete()"
                                        title="Delete" onclick="return confirm('Are you sure?')" >
                                    <i class="icon-trash">
                                    </i>
                                </button>
                            }
                        </td>
                        <td>@slot.SlotId</td>
                        <td>@slot.SlotName</td>
                        <td>@slot.FromDate</td>
                        <td>@slot.ToDate</td>
                        <td>@slot.SlotOtherDefinitions</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script ssrc="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    function ConfirmDelete() {
        var x = confirm("Are you sure you want to delete?");
        if (x)
            return true;
        else
            return false;
    }
</script>
<script src="~/Content/vendors/js/jquery.min.js"></script>
<script src="~/Content/vendors/js/popper.min.js"></script>
<script src="~/Content/vendors/js/bootstrap.min.js"></script>
<script src="~/Content/vendors/js/pace.min.js"></script>
<script src="~/Content/vendors/js/toastr.min.js"></script>
<script src="~/Content/vendors/js/perfect-scrollbar.min.js"></script>
<script src="~/Content/vendors/js/coreui.min.js"></script>