StarterProjectV2/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StarterProjectV2.Models
{
    public class Comment
    {
        [Key]
        public string CommentId { get; set; }
        [Required]
        public string PostId { get; set; }
        [Required]
        public string CommentorId { get; set; }
        public string CommentText { get; set; }
        public bool Approval { get; set; }
        public DateTime CommentTime { get; set; }
        public DateTime ApprovalTime { get; set; }
    }
}

StarterProjectV2/Models/EmailandSMSReport.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StarterProjectV2.Models
{
    public class EmailandSMSReport
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string IsSMSSent { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string SlotId { get; set; }
        public DateTime TimeOfDelivery { get; set; }
        public string NotificationType { get; set; }
        [Key]
        [Required]
        public string EmailandSMSReportId { get; set; }
        public string Text { get; set; }
        public string NotificationSerialNo { get; set; }
    }
}

StarterProjectV2/Models/OwnersInfo.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StarterProjectV2.Models
{
    public class OwnersInfo
    {
        [Key]
        public string OwenerId { get; set; }

        [Index("SlotIdIndex", IsUnique = true), MaxLength(128), Required]
        public string SlotId { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string DateOfBirth { get; set; }
        public string SpouseName { get; set; }
        public string MarriageDate { get; set; }
        public string PresentAddress { get; set; }
        public string PermanantAddress { get; set; }
        public string NID { get; set; }
        public string TIN { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }

        public string OwnerSmartId { get; set; }
        public string PicturePath { get; set; }
        public string NoofSlots { get; set; }
        public string AdditionalId { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string Remarks { get; set; }
        public string AdditionalInformation { get; set; }
        public string UnknownColumn { get; set; }

        public string NIDFilePath { get; set; }
        public string TINFilePath { get; set; }
        public DateTime OwnersLastEditTime { get; set; }
        public string AdminComment { get; set; }
        public string Password { get; set; }
        public string OwnerSegment { get; set; }
        public string IsEditApproved { get; set; }
        public DateTime AdminLastEditApprovedTime { get; set; }
        public string RoutingNo { get; set; }
    }

    public class OwnerBasicInfo
    {
        public string OwnerId { get; set; }
        public string SlotId { get; set; }
        public string Name { get; set; }

    }
}

StarterProjectV2/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StarterProjectV2.Models
{
    public class Post
    {
        [Key]
        public string PostId { get; set; }
        public string PostedBy { get; set; }
        public string PostText { get; set; }
        public DateTime Time { get; set; }
        public int NoOfLikes { get; set; }
        public bool Approval { get; set; }
        public DateTime ApprovalTime { get; set; }
        public string PostHeader { get; set; }
    }
}

StarterProjectV2/ViewModels/CalendarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using StarterProjectV2.Models;


namespace StarterProjectV2.ViewModels
{
    public class CalendarViewModel
    {
        public string[,] calendarMatrix;
        public string[,] calendarMatrixColor;
        public string[,] calendarMatrixBookingId;
        public List<string> colorlist1;
        public List<string> colorlist2;
        int point1 = 0, point2 = 0;
        public int Offset;
        public void GenerateColor()
        {
            colorlist1 = new List<string>();
            colorlist2 = new List<string>();
            string red = "#fa8c8c";
            string blue = "#99aef8";
            string green = "#aef876";
            string yellow = "#e7f72f";
            string pink = "#f263cf";
            string orange = "#fbbe6d";
            colorlist2.Add(red);
            colorlist2.Add(blue);
            colorlist2.Add(pink);

            colorlist1.Add(yellow);
            colorlist1.Add(green);
            colorlist1.Add(orange);
        }
        public string Next(int col)
        {
            if ((col & 1) == 0)
            {
                point1++;
                if (point1 == colorlist1.Count) point1 = 0;
                return colorlist1[point1];
            }
            else
            {
                point2++;
                if (point2 == colorlist2.Count) point2 = 0;
                return colorlist2[point2];
            }
        }
        public void setMatrix(int row, int col, string slotid, int days, int rooms, string bookingId)
        {
            string color ;
            if(col == 0) { color = "red";}
            else color = Next(col);
            for (int k = 0; k < days; k++)
            {
                if (col + k > 15) break;
                for (int k2 = 0; k2 < rooms; k2++)
                {
                    //CalendarViewmodel.setMatrix(j + k2, i + k, slotid, false);

                    calendarMatrix[row + k2, col + k] = slotid;
                    calendarMatrixColor[row + k2, col + k] = color;
                    calendarMatrixBookingId[row + k2, col + k] = bookingId;
                }
            }
            
            return;
        }
    }
}

StarterProjectV2/ViewModels/CommentView.cs
using StarterProjectV2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StarterProjectV2.ViewModels
{
    public class CommentViewFromAdminSite
    {
        public Comment Comment { get; set; }
        public string CommentorName { get; set; }
    }
}

StarterProjectV2/ViewModels/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StarterProjectV2.ViewModels
{
    public class CommentViewModel
    {
        public string PostedBy { get; set; }
        public string PostText { get; set; }
        public string PostHeader { get; set; }
        public string CommentId { get; set; }
        public string PostId { get; set; }
        public string CommentorId { get; set; }
        public string OwnersName { get; set; }
        public string CommentText { get; set; }
        public bool Approval { get; set; }
        public DateTime CommentTime { get; set; }
        public string PosterName { get; set; }
    }
}

StarterProjectV2/Controllers/OwnersInfoController.cs
using StarterProjectV2.Models;
using StarterProjectV2.Services;
using StarterProjectV2.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace StarterProjectV2.Controllers
{
    public partial class OwnersInfoController : Controller
    {
        private readonly BookingService _bookingService = new BookingService();
        private readonly ConfigurationService _configurationService = new ConfigurationService();
        private readonly CommonService _commonService = new CommonService();
        private readonly ApplicationDbContext _dbContext = new ApplicationDbContext();
        private readonly OwnerInfoService _ownerInfoService = new OwnerInfoService();
        private readonly FileService _fileService = new FileService();

        public bool IsUserLoggedIn()
        {
            //return true;
            return !string.IsNullOrEmpty(Session[SessionKeys.USERNAME] as string);
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetSlotIdList(string term)
        {
            List<Select2Model> list = _commonService.GetSlotIdList(term);

            return Json(new { items = list }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CalendarView(int offset = 0)
        {
            if (!IsUserLoggedIn())
                return RedirectToAction("Login", "Accounts");

            TempData["CalendarView"] = "CalendarView";


            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {
                var today = DateTime.Today.AddDays(15 * offset);
                var finalDate = today.AddDays(15);

                ////Get Booking Information
                List<OwnerRoomBooking> selectedBookings = adbc.OwnerRoomBookings.Where(o => o.CheckOutDate >= today && o.CheckInDate < finalDate && o.IsBookingCompleted != "Cancelled").ToList();
                if (offset < 0)
                {
                    selectedBookings = selectedBookings.Where(o => o.HasStayedOrNot == "Yes").ToList();
                }
                else if (offset == 0)
                {
                    selectedBookings = selectedBookings.Where(o => o.HasStayedOrNot == "Yes" || ((o.HasStayedOrNot == "No" || String.IsNullOrEmpty(o.HasStayedOrNot)) && o.CheckInDate >= today)).ToList();
                }

                ////Initialize Matrix
                int i = 0; var date = today;
                String[,] matrix = new String[40, 16];
                string[,] matrixColor = new string[37, 16];
                string[,] matrixBooking = new string[37, 16];
                var CalendarViewmodel = new CalendarViewModel()
                {
                    calendarMatrix = matrix,
                    calendarMatrixColor = matrixColor,
                    calendarMatrixBookingId = matrixBooking,
                    Offset = offset
                };
                CalendarViewmodel.GenerateColor();
                for (i = 1; i < 16; i++)
                {
                    int j = 1;
                    for (; j <= 36; j++)
                    {
                        CalendarViewmodel.calendarMatrix[j, i] = "";
                        CalendarViewmodel.calendarMatrixColor[j, i] = "#FFFFFF";
                    }
                }

                ////Load Matrix
                {
                    ////Today bookings
                    List<OwnerRoomBooking> todayBookings = selectedBookings.Where(o => o.CheckOutDate == today).ToList();
                    int j = 1;
                    foreach (var booking in todayBookings)
                    {
                        var slotid = booking.SlotId;
                        var rooms = booking.NoOfRoomRequested;
                        var bookingId = booking.OwnerRoomBookngId;

                        CalendarViewmodel.setMatrix(j, 0, slotid, 1, rooms, bookingId);
                        j += rooms;
                    }

                    ////Previous bookings
                    List<OwnerRoomBooking> previousBookings = selectedBookings.Where(o => o.CheckOutDate >= today && o.CheckInDate < today).ToList();
                    j = 1;
                    foreach (var booking in previousBookings)
                    {
                        var days = Convert.ToInt16((booking.CheckOutDate - today).TotalDays);
                        var rooms = booking.NoOfRoomRequested; // booking.NoOfRoomAllotted
                        var slotid = booking.SlotId;
                        var bookingId = booking.OwnerRoomBookngId;
                        CalendarViewmodel.setMatrix(j, 1, slotid, days, rooms, bookingId);
                        j += rooms;
                    }
                }

                ////today to final day booking
                for (i = 1; i < 16; i++)
                {
                    date = today.AddDays(i - 1);
                    List<OwnerRoomBooking> todayBookings = selectedBookings.Where(o => o.CheckInDate == date).OrderBy(o => Convert.ToInt16((o.CheckOutDate - o.CheckInDate).TotalDays)).ToList();

                    foreach (var booking in todayBookings)
                    {
                        var days = Convert.ToInt16((booking.CheckOutDate - booking.CheckInDate).TotalDays);
                        var rooms = booking.NoOfRoomRequested;
                        var slotid = booking.SlotId;
                        var bookingId = booking.OwnerRoomBookngId;
                        int j = 1, k2;
                        for (; j < 36; j++)
                        {
                            for (k2 = 0; k2 < rooms; k2++)
                            {
                                if (CalendarViewmodel.calendarMatrix[j + k2, i] != "")
                                {
                                    break;
                                }
                            }
                            if (k2 == rooms) break;
                        }
                        CalendarViewmodel.setMatrix(j, i, slotid, days, rooms, bookingId);
                        j += rooms;
                        //i += days;
                    }
                    int roomsReserved = 0;
                    for (int j = 1; j <= 36; j++)
                    {
                        if (CalendarViewmodel.calendarMatrix[j, i] != "")
                            roomsReserved++;
                    }

                    CalendarViewmodel.calendarMatrix[36 + 2, i] = Convert.ToString(roomsReserved);


                    var temp = adbc.ConfigInvRooms.Where(o => o.FromDate <= date && date <= o.ToDate).ToList().LastOrDefault();
                    int inventorycount;
                    inventorycount = (temp != null) ? temp.InventoryCount : 36;
                    CalendarViewmodel.calendarMatrix[36 + 1, i] = Convert.ToString(inventorycount);

                    int roomsAvailable2 = inventorycount - roomsReserved;
                    CalendarViewmodel.calendarMatrix[36 + 3, i] = Convert.ToString(roomsAvailable2);

                }

                return View("CalendarView", CalendarViewmodel);

            }

        }

        public ActionResult CalendarViewReferral(int offset = 0)
        {
            if (!IsUserLoggedIn())
                return RedirectToAction("Login", "Accounts");

            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {
                var today = System.DateTime.Today.AddDays(15 * offset);
                var finalDate = today.AddDays(15);
                List<ReferralBooking> selectedBookings = adbc.ReferralBookings.Where(o => today <= o.CheckOutDate && o.CheckInDate < finalDate).ToList();
                int i = 0; var date = today;
                String[,] matrix = new String[39, 16];
                string[,] matrixColor = new string[37, 16];
                string[,] matrixBooking = new string[37, 16];
                var CalendarViewmodel = new CalendarViewModel()
                {
                    calendarMatrix = matrix,
                    calendarMatrixColor = matrixColor,
                    calendarMatrixBookingId = matrixBooking,
                    Offset = offset
                };
                CalendarViewmodel.GenerateColor();
                for (i = 1; i < 16; i++)
                {
                    int j = 1;
                    for (; j <= 36; j++)
                    {
                        CalendarViewmodel.calendarMatrix[j, i] = "";
                        CalendarViewmodel.calendarMatrixColor[j, i] = "#FFFFFF";
                    }
                }
                {
                    List<ReferralBooking> todayBookings = selectedBookings.Where(o => o.CheckOutDate == today).ToList();
                    int j = 1;
                    foreach (var booking in todayBookings)
                    {
                        var slotid = booking.SlotId;
                        var rooms = booking.NoOfRoomRequested;
                        var bookingId = booking.ReferralBookingId;

                        CalendarViewmodel.setMatrix(j, 0, slotid, 1, rooms, bookingId);
                        j += rooms;
                    }

                    List<ReferralBooking> previousBookings = selectedBookings.Where(o => o.CheckOutDate > today && o.CheckInDate <= today).ToList();
                    j = 1;
                    foreach (var booking in previousBookings)
                    {
                        var days = Convert.ToInt16((booking.CheckOutDate - today).TotalDays);
                        var rooms = booking.NoOfRoomRequested; // booking.NoOfRoomAllotted
                        var slotid = booking.SlotId;
                        var bookingId = booking.ReferralBookingId;
                        CalendarViewmodel.setMatrix(j, 1, slotid, days, rooms, bookingId);

StarterProjectV2/Views/OwnersInfo/CommentView.cshtml
@model StarterProjectV2.ViewModels.CommentViewModel

@{
    ViewData["Title"] = "Approve This Comment";
}
@section HEADERJS{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
}

@section FOOTERJS{
    <script src="~/Content/vendors/js/toastr.min.js"></script>
    <script src="~/Content/vendors/js/coreui.min.js"></script>
}
@section PAGETITLE{
   Comment View
}
<body style="background-color: oldlace">
<h2 class="text-center" style="color:indianred">@ViewData["Title"]</h2>

<div class="card">

    <div class="card-body">

        <div class="form-group row">
            <label class="col-md-1 col-form-label" for="text-input">Comment Id</label>
            @*<div class="col-md-2">
                @Html.TextBoxFor(m => m.CommentId, new { @class = "form-control", placeholder = "Post Id", id = "number-input", name = "number-input", type = "text", @readonly = "readonly" })

            </div>*@
            <div class="col-lg-4 col-md-4 col-sm-4">
                <p style="padding:5px;border-bottom:1px solid #ccc;font-size:15px;">
                    @Html.DisplayFor(m => m.CommentId)
                </p>
            </div>

        </div>
        <div class="form-group row">
            <label class="col-md-1 col-form-label" for="text-input">Commneted By</label>
            @*<div class="col-md-2">

                @Html.TextBoxFor(m => m.CommentorId, new { @class = "form-control", placeholder = "Text", id = "text-input", name = "text-input", type = "text", @readonly = "readonly" })
            </div>*@
            <div class="col-lg-4 col-md-4 col-sm-4">
                <p style="padding:5px;border-bottom:1px solid #ccc;font-size:15px;">
                    @Html.DisplayFor(m => m.CommentorId)
                </p>
            </div>

        </div>
        <div class="form-group row">
            <label class="col-md-1 col-form-label" for="text-input">Commenter Name</label>
            @*<div class="col-md-2">

                @Html.TextBoxFor(m => m.OwnersName, new { @class = "form-control", placeholder = "Text", id = "text-input", name = "text-input", type = "text", @readonly = "readonly" })
            </div>*@
            <div class="col-lg-4 col-md-4 col-sm-4">
                <p style="padding:5px;border-bottom:1px solid #ccc;font-size:15px;">
                    @Html.DisplayFor(m => m.OwnersName)
                </p>
            </div>

        </div>
        <div class="form-group row">
            <label class="col-md-1 col-form-label" for="text-input">Comment Text</label>
            @*<div class="col-md-5">
                @Html.TextAreaFor(m => m.CommentText, new { @class = "form-control", placeholder = "Number", id = "number-input", name = "number-input", type = "text", @readonly = "readonly" })

            </div>*@
            <div class="col-lg-4 col-md-4 col-sm-4">
                <p style="padding:5px;border-bottom:1px solid #ccc;font-size:15px;">
                    @Html.DisplayFor(m => m.CommentText)
                </p>
            </div>

        </div>
        <div class="form-group row">
            <label class="col-md-1 col-form-label" for="text-input">Poster Name</label>
            @*<div class="col-md-2">

                @Html.TextBoxFor(m => m.PosterName, new { @class = "form-control", placeholder = "Text", id = "text-input", name = "text-input", type = "text", @readonly = "readonly" })
            </div>*@
            <div class="col-lg-4 col-md-4 col-sm-4">
                <p style="padding:5px;border-bottom:1px solid #ccc;font-size:15px;">
                    @Html.DisplayFor(m => m.PosterName)
                </p>
            </div>

        </div>
        <div class="form-group row">
            <label class="col-md-1 col-form-label" for="text-input">Post Title</label>
            @*<div class="col-md-5">
                @Html.TextBoxFor(m => m.PostHeader, new { @class = "form-control", placeholder = "Number", id = "number-input", name = "number-input", type = "text", @readonly = "readonly" })

            </div>*@
            <div class="col-lg-4 col-md-4 col-sm-4">
                <p style="padding:5px;border-bottom:1px solid #ccc;font-size:15px;">
                    @Html.DisplayFor(m => m.PostHeader)
                </p>
            </div>

        </div>
        <div class="form-group row">
            <label class="col-md-1 col-form-label" for="text-input">Post Text</label>
            @*<div class="col-md-5">
                @Html.TextAreaFor(m => m.PostText, new { @class = "form-control", placeholder = "Number", id = "number-input", name = "number-input", type = "text", @readonly = "readonly" })

            </div>*@
            <div class="col-lg-4 col-md-4 col-sm-4">
                <p style="padding:5px;border-bottom:1px solid #ccc;font-size:15px;">
                    @Html.DisplayFor(m => m.PostText)
                </p>
            </div>

        </div>
    </div>
    <div class="card-footer">
        @{
            if (Model.Approval == false)
            {
                <button type="submit" class="submit btn btn-sm btn-success" onclick="location.href = '@Url.Action("CommentApprove", "OwnersInfo", new {commentId = Model.CommentId})'">
                    <i class="fa fa-dot-circle-o"></i> Approve
                </button>
            }
            else
            {
                <button type="submit" class="active btn btn-sm btn-success" disabled>
                    <i class="fa fa-dot-circle-o"></i> Approved
                </button>
            }
        }


        <button type="reset" class="reset btn btn-sm btn-danger" onclick="location.href = '@Url.Action("CommentDelete", "OwnersInfo", new {commentId = Model.CommentId})'">
            <i class="fa fa-ban"></i> Delete
        </button>
        <button type="button" class="btn btn-sm btn-primary m-1" onclick="javascript:window.history.back();">
            <i class="fa fa-angle-left"></i> Back
        </button>
    </div>
</div>
</body>
<script>
    $(document).ready(function () {
        $(document).ready(function () {
            $("#newItem").remove();
            $("#editItem").remove();
            $("#saveItem").remove();
            $("#deleteItem").remove();
            $('#printItem').click(function () {
                window.print();
            });
            $('#reloadItem').click(function () {
                location.reload();
            });
            $("#reportItem").remove();
            $("#dashboardItem").click(function () {
            });
        });
    });
</script>

StarterProjectV2/Views/OwnersInfo/OwnerRoomBookingReports.cshtml
@{
    ViewBag.Title = "Owner Room Booking Reports";
    //Layout = "";
}

@*<h2>OwnerRoomBookingReports</h2>*@

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
@section HEADERJS{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
}

@section FOOTERJS{
    <script src="~/Content/vendors/js/toastr.min.js"></script>
    <script src="~/Content/vendors/js/coreui.min.js"></script>
}
@section PAGETITLE{
   Reports
}
<h2 class="text-center" style="color:indianred">@ViewData["Title"]</h2>
<div class="card m-1" style="margin-bottom: 0">

    <div class="table-responsive-lg" id="table">

        <table id="mainTable1" data-pagination="true" class="table  table-light  table-hover" style="margin-bottom: 0">
            <thead style="color: white; background-color:#315152">
                <tr>
                    <th scope="col">Report Name</th>
                    <th scope="col">Preview</th>
                </tr>
            </thead>
            <tbody>


                <tr>

                    <td>
                        <h4>Owner Booking History Report</h4>
                    </td>
                    <td>
                        <button type="button"
                                class="btn btn-light"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title="View"
                                onclick="location.href = '@Url.Action("OwnerBookingHistoryReport", "OwnersInfo")'">
                            <i class="icon-eye">
                            </i>
                        </button>
                    </td>

                </tr>

                <tr>

                    <td>
                        <h4>Owner Bank Advise Report</h4>
                    </td>
                    <td>
                        <button type="button"
                                class="btn btn-light"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title="View"
                                onclick="location.href = '@Url.Action("OwnerBankAdviseReport", "OwnersInfo")'">
                            <i class="icon-eye">
                            </i>
                        </button>
                    </td>

                </tr>
                <tr>


                    <td>
                        <h4>Owner Departure Report</h4>
                    </td>
                    <td>
                        <button type="button"
                                class="btn btn-light"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title="View"
                                onclick="location.href = '@Url.Action("OwnerDepartureReport", "OwnersInfo")'">
                            <i class="icon-eye">
                            </i>
                        </button>
                    </td>

                </tr>
                <tr>


                    <td>
                        <h4>Owner In House Report</h4>
                    </td>
                    <td>
                        <button type="button"
                                class="btn btn-light"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title="View"
                                onclick="location.href = '@Url.Action("OwnerInHouseReport", "OwnersInfo")'">
                            <i class="icon-eye">
                            </i>
                        </button>
                    </td>

                </tr>
                <tr>


                    <td>
                        <h4>Owner Occupancy Status Report</h4>
                    </td>
                    <td>
                        <button type="button"
                                class="btn btn-light"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title="View"
                                onclick="location.href = '@Url.Action("OwnerOccupancyStatusReport", "OwnersInfo")'">
                            <i class="icon-eye">
                            </i>
                        </button>
                    </td>

                </tr>

                <tr>

                    <td>
                        <h4>Owner Booking Cancellation Report</h4>
                    </td>
                    <td>
                        <button type="button"
                                class="btn btn-light"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title="View"
                                onclick="location.href = '@Url.Action("OwnerBookingCancellationReport", "OwnersInfo")'">
                            <i class="icon-eye">
                            </i>
                        </button>
                    </td>

                </tr>


            </tbody>
        </table>
    </div>
</div>
<div class="table-responsive-lg" id="js-table">
    <table id="dtBasicExample" data-pagination="true" class="table table-hover table-dark" style="margin-bottom: 0"></table>
</div>
<div class="text-center" id="message">

</div>

@*<script>
        $("#" + @Model.index).addClass("active");
    </script>*@

<script>
    var clicked = false;
    $("#Select").on("click", function () {
        $(".form-check-input").prop("checked", !clicked);
        clicked = !clicked;
    });
    $(document).ready(function () {

        $("#newItem").remove();
        $("#editItem").remove();
        $("#dashboardItem").remove();
        $("#saveItem").remove();
        $("#deleteItem").remove();
        $('#printItem').click(function () {
            window.print();
        });

        $('#reloadItem').click(function () {
            location.reload();
        });
        $("#reportItem").remove();


    });
</script>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
<script src="~/Content/vendors/js/jquery.min.js"></script>
<script src="~/Content/vendors/js/popper.min.js"></script>
<script src="~/Content/vendors/js/bootstrap.min.js"></script>
<script src="~/Content/vendors/js/pace.min.js"></script>
<script src="~/Content/vendors/js/toastr.min.js"></script>
<script src="~/Content/vendors/js/perfect-scrollbar.min.js"></script>
<script src="~/Content/vendors/js/coreui.min.js"></script>