StarterProjectV2/ViewModels/RoleDetailsView.cs
using StarterProjectV2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace StarterProjectV2.ViewModels
{
    public class RoleDetailsView
    {
        public string RoleName { get; set; }
        public List<string> RoleList { get; set; }
        public List<Tuple<Module, List<Task>>> GetAllModuleListWithTasks { get; set; }
        //public List<Tuple<string, List<Tuple<string,string>>>> GetSelectedModuleListWithTasks { get; set; }
        public List<PartialUserDetailsViewModel> PartialUserDetailsViewModels { get; set; }

        //public IEnumerable<string> dummy { get; set; }
        public List<Tuple<string, string>> TaskWithRoles { get; set; }
        public IEnumerable<Module> ModuleIdandParent { get; set; }
        public string selectedModuleId { get; set; }
    }
}

StarterProjectV2/Controllers/RoleController.cs
using StarterProjectV2.Models;
using StarterProjectV2.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Logical;
using System.Text;
using System.IO;

namespace StarterProjectV2.Controllers
{
    public class RoleController : Controller
    {
        private static Random RNG = new Random();
        public bool IsUserLoggedIn()
        {
            //return true;
            return !string.IsNullOrEmpty(Session[SessionKeys.USERNAME] as string);
        }

   [HttpGet]
        public ActionResult RoleManagement(string flg)
        {
            if (!IsUserLoggedIn())
            {
                return RedirectToAction("Login", "Accounts", new { });
            }
            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {
                var UserObject = adbc.UserRoles.GroupBy(u => u.RoleName).Select(x => x.FirstOrDefault());
                var UsersWithCreatedRoles = adbc.UserRoles.Select(u => u.RoleName).Distinct().ToList();
                var UserObjectWithRoles = new List<UserRole>();
                foreach (var user in UserObject)
                {
                    if (UsersWithCreatedRoles.Contains(user.RoleName))
                    {
                        UserObjectWithRoles.Add(user);
                    }
                }

                string taskId = adbc.Tasks.Where(u => u.TaskPath == "Role\\RoleManagement").Select(u => u.TaskId).FirstOrDefault();
                var myRoleList = (List<UserRole>)Session[SessionKeys.ROLE_LIST];

                string taskRoles = "";
                foreach (var tasks in myRoleList)
                {
                    if (tasks.TaskId == taskId)
                    {
                        taskRoles = tasks.Details;
                    }
                }

                if (taskRoles != "")
                {
                    if (taskRoles[0] == '0')
                    {
                        return View("Error");
                    }


                }
                else
                {
                    return View("Error");

                }



                List<UserRole> selectedUser = new List<UserRole>();
            
                var model = new RoleList()
                {
                    index = 1,
                    //noOfPage = noOfPage,
                    userDetailsList = UserObjectWithRoles,
                    //TaskRoles = taskRoles,
                    //Users = UserObjectWithRoles,
                    flg = (flg == "false") ? "false" : "true"
                };
                return View(model);
            }

        }
        [HttpPost]
        public ActionResult RoleDelete(string RoleName)
        {
            if (!IsUserLoggedIn())
            {
                return RedirectToAction("Login", "Accounts", new { });
            }

            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {
                string taskId = adbc.Tasks.Where(u => u.TaskPath == "Role\\RoleManagement").Select(u => u.TaskId).FirstOrDefault();
                var myRoleList = (List<UserRole>)Session[SessionKeys.ROLE_LIST];

                string taskRoles = "";
                foreach (var tasks in myRoleList)
                {
                    if (tasks.TaskId == taskId)
                    {
                        taskRoles = tasks.Details;
                    }
                }


                if (taskRoles[4] == '0')
                {
                    return View("Error");
                }

                var delObj = adbc.UserRoles.Where(u => u.RoleName == RoleName).ToList();
                var delUser = adbc.UserRoles.Where(u => u.RoleName == RoleName).FirstOrDefault();
                foreach (var userDetail in delObj)
                {
                    adbc.UserRoles.Remove(userDetail);
                }

                if (delUser != null)
                {
                    adbc.UserRoles.Remove(delUser);
                }
                adbc.SaveChanges();
                return RedirectToAction("RoleManagement");
            }
        }


        [HttpGet]
        public ActionResult RoleDetailsView(string RoleName)
        {
            if (!IsUserLoggedIn())
            {
                return RedirectToAction("Login", "Accounts", new { });
            }
            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {
                var UserDetailsList = adbc.UserRoles.Where(u => u.RoleName == RoleName).ToList();
                var TaskObject = adbc.Tasks.ToList();
                //                        var ModuleObject = db.Modules.Select(m=>m.ModuleName).ToList();
                var ModuleObject = adbc.Modules.ToList();
                var query = (from a in TaskObject
                             join b in ModuleObject
                                 on a.moduleId equals b.ModuleId into f
                             from b in f.DefaultIfEmpty()
                             group new { a } by b.ModuleId
                    into g
                             select new
                             {
                                 Module = adbc.Modules.Where(m => m.ModuleId == g.Key)
                                     .FirstOrDefault(),
                                 TaskList = g.ToList()
                             }).ToList();

                List<Tuple<Module, List<Task>>> list =
                    new List<Tuple<Module, List<Task>>>();


                foreach (var q in query)
                {
                    List<Task> tempList = new List<Task>();
                    for (int i = 0; i < q.TaskList.Count; i++)
                    {
                        tempList.Add(q.TaskList[i].a);
                    }

                    Tuple<Module, List<Task>> obj = Tuple.Create(q.Module, tempList);
                    list.Add(obj);
                }

                var allModuleTaskList = list;


                List<Tuple<string, string>> ListofTasksWithRolesFromUserDetails = new List<Tuple<string, string>>();

                var listOfPrivileges = adbc.UserRoles.Where(u => u.RoleName == RoleName).ToList();

                foreach (var UserDetail in listOfPrivileges)
                {
                    ListofTasksWithRolesFromUserDetails.Add(Tuple.Create(UserDetail.TaskId, UserDetail.Details));
                }

                var mdl = adbc.UserRoles.Where(u => u.RoleName == RoleName).FirstOrDefault();

                var model = new RoleDetailsView()
                {
                    RoleName = RoleName,
                    GetAllModuleListWithTasks = allModuleTaskList,
                    TaskWithRoles = ListofTasksWithRolesFromUserDetails
            
                    //Password = (mdl.Password != "1234") ? EncryptDecryptString.Decrypt(mdl.Password, "1234") : "1234",
        
                };
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult RoleCreate()
        {
            if (!IsUserLoggedIn())
            {
                return RedirectToAction("Login", "Accounts", new { });
            }

            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {
                string taskId = adbc.Tasks.Where(u => u.TaskPath == "Role\\RoleManagement").Select(u => u.TaskId).FirstOrDefault();
                var myRoleList = (List<UserRole>)Session[SessionKeys.ROLE_LIST];
                string taskRoles = "";
                foreach (var tasks in myRoleList)
                {
                    if (tasks.TaskId == taskId)
                    {
                        taskRoles = tasks.Details;
                    }
                }

                if (taskRoles[1] == '0')
                {
                    return View("Error");
                }
                var TaskObject = adbc.Tasks.ToList();
                //                        var ModuleObject = db.Modules.Select(m=>m.ModuleName).ToList();
                var ModuleObject = adbc.Modules.ToList();
                var query = (from a in TaskObject
                             join b in ModuleObject
                                 on a.moduleId equals b.ModuleId into f
                             from b in f.DefaultIfEmpty()
                             group new { a } by b.ModuleId
                    into g
                             select new
                             {
                                 Module = adbc.Modules.Where(m => m.ModuleId == g.Key)
                                     .FirstOrDefault(),
                                 TaskList = g.ToList()
                             }).ToList();

                List<Tuple<Module, List<Task>>> list =
                    new List<Tuple<Module, List<Task>>>();


                foreach (var q in query)
                {
                    List<Task> tempList = new List<Task>();
                    for (int i = 0; i < q.TaskList.Count; i++)
                    {
                        tempList.Add(q.TaskList[i].a);
                    }

                    Tuple<Module, List<Task>> obj = Tuple.Create(q.Module, tempList);
                    list.Add(obj);
                }

                var allModuleTaskList = list;

                var model = new RoleDetailsView()
                {
                    GetAllModuleListWithTasks = allModuleTaskList,
                    //UserTypeList = new List<string>() { "Employee", "Guest" }
                };
                return View(model);
            }
        }
        [HttpPost]
        public JsonResult gettingUserDetailsModel(RoleDetailsView model)
        {
            if (!IsUserLoggedIn())
            {
                return Json("Forbidden Http Request");
            }


            using (ApplicationDbContext adbc = new ApplicationDbContext())
            {

StarterProjectV2/Views/Role/RoleManagement.cshtml
@model StarterProjectV2.ViewModels.RoleList
@{
    ViewBag.Title = "Role Management";
}
@section HEADERJS{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
}


@section FOOTERJS{
    <script src="~/Content/vendors/js/toastr.min.js"></script>
    <script src="~/Content/vendors/js/coreui.min.js"></script>
}
@section PAGETITLE{
   Role Management
}
<div class="alert alert-danger alert-dismissible fade show" id="alert-box" style="display: none" role="alert">
    <strong>You must give the user some privileges.</strong> Click the cross button to dismiss the message.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<body style="background-color: oldlace">
<h2 class="text-center" style="color:indianred">@ViewData["Title"]</h2>

<div class="card" style="margin-bottom: 0">

    <div class="table-responsive-lg">

        <table id="mainTable1" data-pagination="true" class="table  table-light  table-hover" style="margin-bottom: 0">
            <thead style="color: white; background-color:#315152">

            <tr>
                <th scope="col">Role Name</th>
                <th scope="col">View</th>

                <th scope="col">Edit</th>
                @*<th scope="col"> Delete</th>*@
            </tr>
            </thead>
            <tbody>
            @{
                int noOfdata = Model.userDetailsList.Count();
            }
            @if (noOfdata != 0)
            {
                foreach (var us in Model.userDetailsList)
                {
                    <tr>
                        <td>@us.RoleName</td>
                        <td>
                            <button type="button"
                                    class="btn btn-light"
                                    data-toggle="tooltip"
                                    data-placement="bottom"
                                    title="View"
                                    onclick="location.href = '@Url.Action("RoleDetailsView", "Role", new { RoleName = us.RoleName })'">
                                <i class="icon-eye">
                                </i>
                            </button>
                        </td>

                        <td>
                            <button type="button"
                                    class="btn btn-light"
                                    data-toggle="tooltip"
                                    data-placement="bottom"
                                    title="Edit"
                                    onclick="location.href = '@Url.Action("RoleEdit", "Role", new { RoleName = us.RoleName })'">
                                <i class="icon-notebook">
                                </i>
                            </button>
                        </td>
                        @*<td>
                            @using (Html.BeginForm("RoleDelete", "Role", new { RoleName = us.RoleName }, FormMethod.Post))
                            {
                                <button type="submit"
                                        class="btn btn-light"
                                        data-toggle="tooltip"
                                        data-placement="bottom"
                                        title="Delete" onclick="return confirm('Are you sure?')" >
                                    <i class="icon-trash">
                                    </i>
                                </button>
                            }
                        </td>*@
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
</div>
</body>
<script>
    $("#" + @Model.index).addClass("active");
</script>
<script>
    var flg = "@Model.flg";
    //alert(flg.length);
    if (flg.length==5) {
        //alert("ggg");
        document.getElementById("alert-box").style.display = "block";
    }
</script>
<script>
    $(document).ready(function() {
        var taskRoles = "@Model.TaskRoles";
        if (taskRoles[0] == '0') {
            $('table tr').find('td:eq(0),th:eq(0)').remove();
            if (taskRoles[3] == '0') {
                $('table tr').find('td:eq(0),th:eq(0)').remove();
                if (taskRoles[4] == '0') {
                    $('table tr').find('td:eq(0),th:eq(0)').remove();
                }
            } else {
                if (taskRoles[4] == '0') {
                    $('table tr').find('td:eq(1),th:eq(1)').remove();
                }
            }
        } else {
            if (taskRoles[3] == '0') {
                $('table tr').find('td:eq(1),th:eq(1)').remove();
                if (taskRoles[4] == '0') {
                    $('table tr').find('td:eq(1),th:eq(1)').remove();
                }
            } else {
                if (taskRoles[4] == '0') {
                    $('table tr').find('td:eq(2),th:eq(2)').remove();
                }
            }
        }
        if (taskRoles[1] == '0') {
            $("#newItem").remove();
        }
    });
</script>
<script>
    var clicked = false;
    $("#Select").on("click", function () {
        $(".form-check-input").prop("checked", !clicked);
        clicked = !clicked;
    });


    $(document).ready(function() {
        $("#newItem").click(function() {
            document.location = '@Url.Action("RoleCreate", "Role")';

        });
        $("#editItem").remove();
        $("#saveItem").remove();
        $("#deleteItem").remove();

        $("#reportItem").remove();
        $("#dashboardItem").remove();

        $('#reloadItem').click(function() {
            location.reload();
        });
        $('#printItem').click(function () {
            window.print();
        });


    });
</script>
<script>

    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
<script src="~/Content/vendors/js/jquery.min.js"></script>
<script src="~/Content/vendors/js/popper.min.js"></script>
<script src="~/Content/vendors/js/bootstrap.min.js"></script>
<script src="~/Content/vendors/js/pace.min.js"></script>
<script src="~/Content/vendors/js/toastr.min.js"></script>
<script src="~/Content/vendors/js/perfect-scrollbar.min.js"></script>
<script src="~/Content/vendors/js/coreui.min.js"></script>